// Generated by CoffeeScript 1.6.3
// ==UserScript==
// @name        Hide LoLNexus Rankings
// @namespace   FichteFoll
// @author      FichteFoll
// @description Want to know who you're playing against but don't care about ratings? Use this.
// @include     http://lolnexus.com/*/search*
// @include     http://www.lolnexus.com/*/search*
// @version     0.2.0
// @grant       none
// @require     https://userscripts.org/scripts/source/145813.user.js
// ==/UserScript==
;
/* jshint newcap:false*/

/* global jQuery:true*/

/* global GM_setValue:true, GM_getValue:true*/

var $, $rank_cells, add_toggle_button, auto_hide, cells_hidden, toggle_rankings;

$ = jQuery;

$rank_cells = false;

cells_hidden = false;

auto_hide = GM_getValue("auto_hide", false) === 'true';

add_toggle_button = function() {
  $(".vs").html("<a id=\"rank-toggle\" class=\"blue-button\" href=\"#\" style=\"font-size: 12px; margin-right: 20px;\">\n  Toggle rankings</a>\nVS\n<input id=\"save-toggle\" type=\"checkbox\" style=\"margin-left: 20px;\" " + (auto_hide && "checked" || '') + " />\n<!-- I have to add some margin-right here because otherwise the S3 column\nheader (!!) would lay above the checkbox. Fuck knows. -->\n<span style=\"margin-right: 50px\">\n  Auto Hide</span>");
  $("#rank-toggle").click(function() {
    toggle_rankings();
    return false;
  });
  return $("#save-toggle").change(function() {
    GM_setValue("auto_hide", this.checked);
    return true;
  });
};

toggle_rankings = function(duration) {
  if (duration == null) {
    duration = 500;
  }
  $rank_cells.animate({
    "opacity": Number(cells_hidden)
  }, duration);
  return cells_hidden = !cells_hidden;
};

/* MAIN*/


$(document).ready(function() {
  var check_for_cells;
  check_for_cells = function(tries) {
    if (tries == null) {
      tries = 1;
    }
    if (tries === 60) {
      return;
    }
    if ($(".error").length || $(".header-bar h2 small").html() === "Region Disabled") {
      return console.log("summoner not in game (or region disabled or unable to query server or ...)");
    }
    $rank_cells = $(".ranking");
    if (!$rank_cells.length) {
      setTimeout((function() {
        return check_for_cells(tries + 1);
      }), 100);
      return;
    }
    if (auto_hide) {
      toggle_rankings(0);
    }
    return add_toggle_button();
  };
  return check_for_cells();
});

console.log("hi");
