// Generated by CoffeeScript 1.6.3
// ==UserScript==
// @name        Hide LoLNexus Rankings
// @namespace   FichteFoll
// @author      FichteFoll
// @description Want to know who you're playing against but don't care about ratings? Use this.
// @include     http://lolnexus.com/*
// @version     0.1.0
// @grant       none
// @require     https://userscripts.org/scripts/source/145813.user.js
// ==/UserScript==
;
/* **TODO**
#
# -? Instead of animating opacity, animate width (DOESN'T WORK)
# -? Add a checkbox to each header to toggle it individually
*/

/* jshint newcap:false*/

/* global jQuery:true*/

/* global GM_setValue:true, GM_getValue:true, GM_deleteValue:true*/

var $, $rank_cells, add_toggle_button, auto_hide, cells_hidden, toggle_rankings;

$ = jQuery;

$rank_cells = false;

cells_hidden = false;

auto_hide = GM_getValue("auto_hide", false) === 'true';

add_toggle_button = function() {
  var cells, i, row_widths, _i;
  cells = $(".row-fluid").children();
  row_widths = [1, 2, 3, 2, 1];
  for (i = _i = 0; _i < 5; i = ++_i) {
    cells[i].className = "span" + row_widths[i];
  }
  $("<div class=\"span3 row-fluid\" id=\"rank-toggle-div\" style=\"text-align: center\">\n  <div id=\"toggle\" class=\"span7 row-fluid\" style=\"text-align:center; color:#f4f4f4\">\n    <a id=\"rank-toggle\" class=\"btn btn-large btn-customBlue\" href=\"#\">\n      Toggle rankings</a>\n  </div>\n  <input id=\"save-toggle\" type=\"checkbox\" style=\"height: 34px;\" " + (auto_hide && "checked" || '') + ">\n    Auto Hide\n  </input>\n</div>").insertAfter(cells[2]);
  $("#rank-toggle").click(function() {
    return toggle_rankings();
  });
  return $("#save-toggle").change(function() {
    return GM_setValue("auto_hide", this.checked);
  });
};

toggle_rankings = function(duration) {
  if (duration == null) {
    duration = 500;
  }
  $rank_cells.animate({
    "opacity": Number(cells_hidden)
  }, duration);
  return cells_hidden = !cells_hidden;
};

/* MAIN*/


$(document).ready(function() {
  $rank_cells = $("table[id^=set] td > img[src^='images/medals']").parent();
  if (!$rank_cells.length) {
    return;
  }
  if (auto_hide) {
    toggle_rankings(0);
  }
  return add_toggle_button();
});
